'use client'
import React from 'react';
import './globals.css'
import "react-responsive-carousel/lib/styles/carousel.min.css"; 


export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children, session }) {

  return (
    <html lang="en">
           
      <body className='bg-gray-100'>
     
        {children}
        
        </body>
       
     
    </html>
  )
}
